### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by jaejlf** [jaejlf/Stock-Village#6]
## Deadline 08.08.sun

- 포트폴리오 종목 → 관심 종목으로 변경

- [ ] 포트폴리오 편집 페이지 → 관심 종목 레이어 체크로 수정
- [ ] portfolio 스크립트 내용 수정 (scriptable object)
- [ ] 내용 변경에 따른 기타 수정 사항

<br/>

- 유튜브 데이터

- [ ] Youtube Data API v3. 사용 테스트
- [ ] 유튜브 데이터 세부 분석 내용 정하기
